.TH md2d "Version: 2.0"
.SH 
md2d construction log
.B DATE:
.RB 01.19.02
.RB 10pm

I think 
.I md2d
program is finally ready.  Tested a few basic stuffs, like timing and stability
and, velocity and force distribution.  I think it's in working condition.

Important things that need to be added at this point are pressure calculation, energy
accumulation calculation, including temperature fluctuation from kinetic
energy.  Also, I need to set up the output sequence better, including restart
and thermo, which actually are still incomplete.

